export type {
  Point,
  HexPoint,
  Size,
  Rect,
  ChunkType,
  HexEdge,
  HexEdgeConnection,
  Chunk,
  ElementType,
  MapElement,
  ConnectionStyle,
  ChunkConnection,
  ViewLevel,
  MapData,
  MapMeta,
  Map,
  EditorTool,
  EditorState,
  CreateChunkOptions,
  UpdateChunkOptions,
  CreateElementOptions,
  UpdateElementOptions,
  CreateConnectionOptions,
  UpdateConnectionOptions,
  CreateMapOptions,
  UpdateMapOptions,
  HistoryEntry
} from '../../../shared/map'

export type MapTool = EditorTool

export {
  CHUNK_TYPE_CONFIG,
  ELEMENT_TYPE_CONFIG,
  HEX_SIZE,
  HEX_EDGE_NAMES,
  DEFAULT_CANVAS_WIDTH,
  DEFAULT_CANVAS_HEIGHT,
  DEFAULT_BACKGROUND_COLOR,
  DEFAULT_CONNECTION_COLOR,
  DEFAULT_CONNECTION_LINE_WIDTH,
  generateId,
  hexToPixel,
  pixelToHex,
  hexRound,
  hexDistance,
  getHexNeighbors,
  getHexCorners,
  createDefaultHexEdges,
  createDefaultChunk,
  createDefaultElement,
  createDefaultConnection,
  createDefaultMapData,
  getHexEdgeCenter,
  checkHexEdgeCompatibility,
  findBestEdges,
  findElementById,
  updateElementInTree,
  deleteElementFromTree,
  getParentPath
} from '../../../shared/map'
