export { default as SettingsPage } from './SettingsPage'
export { EditorSettings } from './EditorSettings'
export { HighlightSettings } from './HighlightSettings'
export { default as LayoutSettings } from './LayoutSettings'
export { ShortcutsSettings } from './ShortcutsSettings'
export { ApiSettings } from './ApiSettings'
export { BackupSettings } from './BackupSettings'
export { DataManagementSettings } from './DataManagementSettings'
